apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: welcome-app
  name: welcome-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: welcome-app
    spec:
      containers:
      - name: welcome-app
        image: avknsk/welcome-app:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 150m
            memory: 128Mi